//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by gh0st.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_GH0STTYPE                   129
#define IDD_BUILD                       131
#define IDD_FILE                        132
#define IDR_LIST                        133
#define IDC_DRAG                        134
#define IDC_MUTI_DRAG                   135
#define IDC_CURSOR3                     136
#define IDC_CURSOR4                     137
#define IDD_SETTINGS                    140
#define IDR_FILEMANAGER                 146
#define IDR_TOOLBAR1                    147
#define IDB_TOOLBAR                     149
#define IDB_TOOLBAR_ENABLE              149
#define IDR_TOOLBAR2                    154
#define IDR_LOCAL_VIEW                  156
#define IDR_REMOTE_VIEW                 157
#define IDB_TOOLBAR_DISABLE             158
#define IDD_TRANSFERMODE_DLG            159
#define IDD_SCREENSPY                   160
#define IDD_DOWNEXEC                    162
#define IDD_WEBCAM                      163
#define IDI_WEBCAM                      164
#define IDB_ARROWDOWN                   165
#define IDB_ARROWUP                     166
#define IDD_KEYBOARD                    167
#define IDD_NEWFOLDER                   168
#define IDD_SYSTEM                      169
#define IDR_PSLIST                      170
#define IDD_SHELL                       171
#define IDR_BSS                         173
#define IDI_CMDSHELL                    177
#define IDI_KEYBOARD                    178
#define IDI_SYSTEM                      179
#define IDC_DOT                         182
#define IDR_MINIMIZE                    183
#define IDD_AUDIO                       184
#define IDI_AUDIO                       185
#define IDC_LIST_REMOTE                 1005
#define IDC_LIST_LOCAL                  1006
#define IDC_LOCAL_PATH                  1007
#define IDC_REMOTE_PATH                 1008
#define IDC_STATIC_REMOTE               1009
#define IDC_CONFIRM                     1010
#define IDC_PORT                        1011
#define IDC_LISTEN_PORT                 1011
#define IDC_OVERWRITE                   1012
#define IDC_CONNECT_MAX                 1012
#define IDC_ADDITION                    1013
#define IDC_JUMP                        1014
#define IDC_OVERWRITE_ALL               1015
#define IDC_ADDITION_ALL                1016
#define IDC_JUMP_ALL                    1017
#define IDC_CANCEL                      1018
#define IDC_TIPS                        1019
#define IDC_URL                         1021
#define IDC_ENCODE                      1022
#define IDC_DNS_STRING                  1022
#define IDC_REMOTE_HOST                 1023
#define IDC_REMOTE_PORT                 1024
#define IDC_PROXY_HOST                  1025
#define IDC_PROXY_PORT                  1026
#define IDC_PROXY_USER                  1027
#define IDC_PROXY_PASS                  1028
#define IDC_EDIT                        1029
#define IDC_RESETPORT                   1030
#define IDC_FOLDERNAME                  1031
#define IDC_LIST_PROCESS                1034
#define IDC_TAB                         1035
#define IDC_LIST_WINDOWS                1036
#define IDC_LIST_DIALUPASS              1037
#define IDC_BUILD                       1038
#define IDC_CONNECT_AUTO                1040
#define IDC_STATIC_VER                  1041
#define IDC_ENABLE_HTTP                 1043
#define IDC_CHECK_AUTH                  1048
#define IDC_CHECK_PROXY                 1049
#define IDC_TEST_PROXY                  1050
#define IDC_TEST_MASTER                 1051
#define IDC_SYSTEM_TIPS                 1052
#define IDC_DISABLE_POPTIPS             1053
#define IDC_SEND_LOCALAUDIO             1054
#define IDC_SAVEAS_DEFAULT              1054
#define IDC_SERVICE_DISPLAYNAME         1058
#define IDC_SERVICE_DESCRIPTION         1059
#define ID_LOCAL_TOOLBAR                0x5001
#define ID_REMOTE_TOOLBAR               0x5002
#define ID_APP_PWD                      32771
#define IDM_FILEMANAGER                 32772
#define IDM_SHUTDOWN                    32773
#define IDM_REBOOT                      32774
#define IDM_TRANSFER                    32775
#define IDM_RENAME                      32776
#define IDM_DELETE                      32777
#define IDM_NEWFOLDER                   32778
#define IDM_PROPERTY                    32779
#define IDT_LOCAL_PREV                  32780
#define IDT_LOCAL_COPY                  32781
#define IDT_LOCAL_DELETE                32782
#define IDT_LOCAL_VIEW                  32783
#define IDT_LOCAL_NEWFOLDER             32784
#define IDT_REMOTE_PREV                 32790
#define IDT_REMOTE_COPY                 32791
#define IDT_REMOTE_DELETE               32792
#define IDT_REMOTE_NEWFOLDER            32793
#define IDT_REMOTE_VIEW                 32794
#define IDT_REMOTE_STOP                 32795
#define IDT_LOCAL_STOP                  32797
#define IDM_LOCAL_BIGICON               32798
#define IDM_LOCAL_SMALLICON             32799
#define IDM_LOCAL_LIST                  32800
#define IDM_LOCAL_REPORT                32801
#define IDM_REMOTE_BIGICON              32802
#define IDM_REMOTE_SMALLICON            32803
#define IDM_REMOTE_LIST                 32804
#define IDM_REMOTE_REPORT               32805
#define IDM_SCREENSPY                   32806
#define IDM_DOWNEXEC                    32807
#define IDM_WEBCAM                      32808
#define IDM_REMOVE                      32809
#define IDM_KEYBOARD                    32810
#define IDM_REFRESH                     32811
#define IDM_SYSTEM                      32812
#define IDM_KILLPROCESS                 32813
#define IDM_REFRESHPSLIST               32814
#define IDM_REMOTESHELL                 32815
#define IDM_LOGOFF                      32818
#define IDM_SELECT_ALL                  32820
#define IDM_UNSELECT_ALL                32821
#define IDM_OPEN_URL_SHOW               32825
#define IDM_OPEN_URL_HIDE               32827
#define IDM_CLEANEVENT                  32828
#define IDM_HIDE                        32829
#define IDM_SHOW                        32830
#define IDM_EXIT                        32831
#define IDM_RENAME_REMARK               32832
#define IDM_UPDATE_SERVER               32833
#define IDM_LOCAL_OPEN                  32834
#define IDM_REMOTE_OPEN_SHOW            32836
#define IDM_REMOTE_OPEN_HIDE            32837
#define IDM_AUDIO_LISTEN                32838
#define IDM_DISCONNECT                  32840
#define ID_STAUTSTIP                    59394
#define ID_STAUTSSPEED                  59395
#define ID_STAUTSPORT                   59396
#define ID_STAUTSCOUNT                  59397

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32841
#define _APS_NEXT_CONTROL_VALUE         1060
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
