@echo off
echo ----------------------------------------------------
echo Press any key to delete all files with ending:
echo  *.aps *.idb *.ncp *.obj *.pch *.tmp *.sbr
echo Visual c++/.Net junk 
echo ----------------------------------------------------

del /F /Q /S *.aps *.idb *.ncp *.obj *.ipch  *.log *.pch *.sbr *.tmp *.pdb *.bsc  *.map *.ilk *.res *.ncb *.opt *.suo *.manifest *.dep *.tlog *.sdf  *.plg 


